website/routes.py
'''
This page contains all the main routes, all the login related functions are in the auth.py file
'''

# Imports
from flask import Blueprint, render_template, flash, redirect, url_for, request, jsonify
from flask_login import login_required, current_user
from .models import *
from . import db
from website.helper_functions import create_user
import pandas as pd
from flask import current_app
from . import set_max_team
from werkzeug.security import generate_password_hash
from sqlalchemy.exc import IntegrityError
from sqlalchemy import func
from datetime import datetime, timedelta

#Flask blueprint
routes = Blueprint('main', __name__)

#routes
@routes.route('/')
def home():
    '''
    sees what type of user the current user is and redirects them to their page, if no user is signed up it takes them to the login page
    '''

    if not current_user.is_authenticated:
        return redirect(url_for('auth.login'))

    user = current_user

    if user.type == "admin":
        if current_user.type != "admin":
            return "<h1>NO ACCESS</h1>"

        # Query all athletes and teams
        athletes = User.query.filter_by(type='athlete').all()
        teams = Team.query.all()

        return render_template('admin_dashboard.html', athletes=athletes, teams=teams, user=user)
    
    elif user.type == "peak":
        peak = Peak.query.filter_by(colby_id=current_user.colby_id).first()
        team_association = next((association for association in peak.team_associations if association.role == 'peak'), None)
        
        if team_association is not None:
            team = team_association.team
            athletes = [association.user for association in team.team_associations if association.role == 'athlete']
        else:
            return "<h1>There are no teams</h1>"
    
        return render_template('team_dashboard.html', user=user,team=team, athletes=athletes)
    
    elif user.type == "coach":

        coach = Coach.query.filter_by(colby_id=current_user.colby_id).first()
        team_association = next((association for association in coach.team_associations if association.role == 'coach'), None)
        
        if team_association is not None:
            team = team_association.team
            athletes = [association.user for association in team.team_associations if association.role == 'athlete']
        else:
            return "<h1>There are no teams</h1>"
    
        return render_template('team_dashboard.html', user=user,team=team, athletes=athletes)
    
    elif user.type == "athlete":
        return(redirect(url_for('main.athlete')))
    
    return render_template('login.html')

@routes.route('/athlete')
@login_required
def athlete():
    '''
    this is the page for an user of type athlete, and sees its personal data
    '''
 
    if current_user.type != "athlete":
        return "<h1>NO ACCESS</h1>"
    
    # fetches the date and visible notes
    athlete = current_user
    date = request.args.get('date', None)
    visible_notes = [note for note in athlete.received_notes if note.visible]

    # collects all the different dates the athlete has jumped
    if date == None:
        date = HawkinAthlete.query\
        .filter_by(athlete_id=athlete.colby_id)\
        .order_by(HawkinAthlete.date.desc())\
        .first()
        date = date.date.strftime("%Y-%m-%d")
    dates_query = db.session.query(
        HawkinAthlete.date,
    ).filter(
        HawkinAthlete.athlete_id == athlete.colby_id
    ).distinct().all()
    # Extracting and formatting dates
    distinct_dates = [date[0].strftime("%Y-%m-%d") for date in dates_query]

    # collects the average metrics for the specified day
    avg_metrics = db.session.query(
        func.avg(HawkinAthlete.braking_rfd).label('avg_braking_rfd'),
        func.avg(HawkinAthlete.jump_height).label('avg_jump_height'),
        func.avg(HawkinAthlete.mrsi).label('avg_mrsi'),
        func.avg(HawkinAthlete.peak_propulsive_force).label('avg_peak_propulsive_force')
    ).filter(
        HawkinAthlete.athlete_id == athlete.colby_id,
        HawkinAthlete.date == date
    ).first()

    per = [] # percentage equivalent using the athete max
    circle = [] # value for the graph to reprecent the percentage 

    # RFD
    # m = max, d = datapoint, p = percentage, c = circle
    m = athlete.rfd_max
    d = avg_metrics[0]
    p = (d*100)/m
    c = 251 - (251*(p/100))
    per.append(int(p))
    circle.append(int(c))

    # JH
    m = athlete.jh_max
    d = avg_metrics[1]
    p = (d*100)/m
    c = 251 - (251*(p/100))
    per.append(int(p))
    circle.append(int(c))

    # mrsi
    m = athlete.mrsi_max
    d = avg_metrics[2]
    p = (d*100)/m
    c = 251 - (251*(p/100))
    per.append(int(p))
    circle.append(int(c))

    # ppf
    m = athlete.ppf_max
    d = avg_metrics[3]
    p = (d*100)/m
    c = 251 - (251*(p/100))
    per.append(int(p))
    circle.append(int(c))

    for_avg = [] # list for formated avergaes
    for i in avg_metrics:
        for_avg.append("{:.5g}".format(i))
    
    return render_template('athlete_dashboard.html', athlete=athlete, user=current_user, notes=visible_notes, for_avg=for_avg, per=per, circle=circle, date=date, distinct_dates=distinct_dates)

@routes.route('/team/<int:id>', methods = ['GET', 'POST'])
@login_required
def team(id):
    '''
    this is the page for an user of type coach, peak and admin, shows the average values of the metrics of all athletes in the last 5 days
    '''

    if current_user.type == "athlete": # ensures that the user is not an athelte
        return "<h1>NO ACCESS</h1>"
    
    # fetches the team object, as well as all the athletes in the team
    team = Team.query.get(id)
    team_members = [association.user for association in team.team_associations]
    athletes = [member for member in team_members if member.type == 'athlete']
    colby_ids = [athlete.colby_id for athlete in athletes]

    # Requested date from query parameters or the last jump date if not specified
    date_param = request.args.get('date', None)

    # Collects all the distinct dates for the user to chose the date in the calendar
    jump_dates_query = db.session.query(HawkinAthlete.date).filter(
        HawkinAthlete.athlete_id.in_(colby_ids)
    ).distinct().order_by(HawkinAthlete.date.asc())
    distinct_dates = [result.date.strftime("%Y-%m-%d") for result in jump_dates_query.all()]

    if date_param:
        try:
            # If 'date' query parameter exists, parse it
            date = datetime.strptime(date_param, '%Y-%m-%d').date()
        except ValueError:
            
            # Redirect to the same page without the 'date' parameter
            return redirect(url_for('main.team', id=id))
    else:
        # Sets the date to the last jump of any of the athltetes in the team
        last_jump_date_query = db.session.query(db.func.max(HawkinAthlete.date)).filter(
            HawkinAthlete.athlete_id.in_(colby_ids)
        )
        last_jump_date_result = last_jump_date_query.first()
        last_jump_date = last_jump_date_result[0] if last_jump_date_result[0] else datetime.today().date()
        date = last_jump_date

    # we are going to collect the average values of the athletes of the last 5 days (this is because not everyone jump everyday jump every day)
    start_date = date - timedelta(days=5)
    end_date = date
    avg_metrics = db.session.query(
        func.avg(HawkinAthlete.braking_rfd).label('avg_braking_rfd'),
        func.avg(HawkinAthlete.jump_height).label('avg_jump_height'),
        func.avg(HawkinAthlete.mrsi).label('avg_mrsi'),
        func.avg(HawkinAthlete.peak_propulsive_force).label('avg_peak_propulsive_force')
    ).filter(
        HawkinAthlete.athlete_id.in_(colby_ids),
        HawkinAthlete.date >= start_date,
        HawkinAthlete.date <= end_date
    ).first()

    per = [] # percentage equivalent using the athete max
    circle = [] # value for the graph to reprecent the percentage 

    # RFD
    # m = max, d = datapoint, p = percentage, c = circle
    m = team.rfd_max
    d = avg_metrics[0]
    p = (d*100)/m
    c = 251 - (251*(p/100))
    per.append(int(p))
    circle.append(int(c))

    # JH
    m = team.jh_max
    d = avg_metrics[1]
    p = (d*100)/m
    c = 251 - (251*(p/100))
    per.append(int(p))
    circle.append(int(c))

    # mrsi
    m = team.mrsi_max
    d = avg_metrics[2]
    p = (d*100)/m
    c = 251 - (251*(p/100))
    per.append(int(p))
    circle.append(int(c))

    # ppf
    m = team.ppf_max
    d = avg_metrics[3]
    p = (d*100)/m
    c = 250 - (250*(p/100))
    per.append(int(p))
    circle.append(int(c))

    for_avg = [] # list for formated avergaes
    for i in avg_metrics:
        for_avg.append("{:.5g}".format(i))

    return render_template('team_dashboard.html', team=team, athletes=athletes, user=current_user, current_team_id=id, for_avg=for_avg, per=per, circle=circle, date=date, distinct_dates=distinct_dates)

@routes.route('/athlete/<int:id>', methods = ['GET', 'POST'])
@login_required
def athlete_coach(id):
    '''
    this is the page for an user of type coach, peak, and admin, and sees the data for an athelte
    '''

    if current_user.type == "athlete": # ensure the user is not an athlete
        return "<h1>NO ACCESS</h1>"
    
    #fetches the date, athelte and visible notes
    date = request.args.get('date', None)
    athlete = Athlete.query.get(id)
    visible_notes = [note for note in athlete.received_notes if note.visible]

    # collects all the different dates the athlete has jumped
    if date == None:
        date = HawkinAthlete.query\
        .filter_by(athlete_id=athlete.colby_id)\
        .order_by(HawkinAthlete.date.desc())\
        .first()
        date = date.date.strftime("%Y-%m-%d")
    dates_query = db.session.query(
        HawkinAthlete.date,
    ).filter(
        HawkinAthlete.athlete_id == athlete.colby_id
    ).distinct().all()
    # Extracting and formatting dates

website/templates/athlete_dashboard.html
{% extends 'base.html' %}

{% block title %}Athlete Dashboard{% endblock %}

{% block content %}

<style>
    @keyframes fatigue{100%{stroke-dashoffset: {{circle[0]}};}}
    @keyframes jh{100%{stroke-dashoffset: {{circle[1]}};}}
    @keyframes performance{100%{stroke-dashoffset: {{circle[2]}};}}
    @keyframes power{100%{stroke-dashoffset: {{circle[3]}};}}
</style>

<div class="top">
    <div class="menu" id="menu-btn" style="width: 2rem; height: 2rem;">
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentcolor" class="bi bi-list" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
    </div>
    <h1>Dashboard {{athlete.first_name}} {{athlete.last_name}}</h1>
</div>

<div class="date">
    <input type="text" id="datePicker">
</div>

<div class="insights">
    <div class="metric" onclick="window.location.href='/rRFD/{{ athlete.id }}';" style="cursor: pointer;">
        <span>Fatigue</span>
        <div class="middle">
            <div class="left">
                <h3>Fatigue data</h3>
                <h1>{{ for_avg[0] }}</h1>
            </div>
            <div class="progress">
                <div class="outer">
                    <div class="inner">
                        <div class="num">{{per[0]}}%</div>
                    </div>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
                    <circle style="animation: fatigue 1s linear forwards;"  cx='46' cy='46' r='40' stroke-linecap="round"  />
                </svg>
            </div>
        </div>
        <small class="text-muted">(N/s)</small>
    </div>
    <!-- --------------- End of Fatigue rRFD -------------- -->


    <div class="metric" onclick="window.location.href='/jh/{{ athlete.id }}';" style="cursor: pointer;">
        <span> Jump Height</span>
        <div class="middle">
            <div class="left">
                <h3>Jump Height data</h3>
                <h1>{{ for_avg[1] }}</h1>
            </div>
            <div class="progress">
                <div class="outer">
                    <div class="inner">
                        <div class="num">{{per[1]}}%</div>
                    </div>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
                    <circle style="animation: jh 1s linear forwards;"  cx='46' cy='46' r='40' stroke-linecap="round"  />
                </svg>
            </div>
        </div>
        <small class="text-muted">(Meters)</small>
    </div>
    <!-- --------------- End of Jump Height -------------- -->


    <div class="metric" onclick="window.location.href='/mrsi/{{ athlete.id }}';" style="cursor: pointer;">
        <span> Performance</span>
        <div class="middle">
            <div class="left">
                <h3>Performance data</h3>
                <h1>{{ for_avg[2] }}</h1>
            </div>
            <div class="progress">
                <div class="outer">
                    <div class="inner">
                        <div class="num">{{per[2]}}%</div>
                    </div>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
                    <circle style="animation: performance 1s linear forwards;"  cx='46' cy='46' r='40' stroke-linecap="round"  />
                </svg>
            </div>
        </div>
        <small class="text-muted">Relative units</small>
    </div>
    <!-- --------------- End of Performance -------------- -->


    <div class="metric" onclick="window.location.href='/ppf/{{ athlete.id }}';" style="cursor: pointer;">
        <span>Power</span>
        <div class="middle">
            <div class="left">
                <h3>Power data</h3>
                <h1>{{ for_avg[3] }}</h1>
            </div>
            <div class="progress">
                <div class="outer">
                    <div class="inner">
                        <div class="num">{{per[3]}}%</div>
                    </div>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" version="1.1">
                    <circle style="animation: power 1s linear forwards;"  cx='46' cy='46' r='40' stroke-linecap="round"  />
                </svg>
            </div>
        </div>
        <small class="text-muted">(Newtons)</small>
    </div>
    <!-- --------------- End of Power -------------- -->
</div>
<!-- --------------- End of Insights -------------- -->

<div class="athletes">
    <h2> Personal Notes</h2>
    <table>
        <!-- table body -->
        <tbody>
            {% for note in notes %}
            <tr>
                <td>{{ note.text }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<!-- --------------- End of Athletes -------------- -->

<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

<script>
    var availableDates = {{ distinct_dates | tojson | safe }};

    flatpickr("#datePicker", {
        enableTime: false,
        dateFormat: "Y-m-d",
        defaultDate: "{{date}}",
        enable: availableDates,
        onChange: function(selectedDates, dateStr, instance) {
            const athleteId = '{{ athlete.id }}'; // Make sure the athlete's ID is available
            // Redirect to the Flask route with the selected date as a query parameter
            window.location.href = `/athlete/${athleteId}?date=${dateStr}`;
        }
    });
</script>

{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Font -->
    <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@400;500&display=swap" rel="stylesheet">

    <!-- Charts JS-->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.0"></script>
    <!-- Include the date-fns adapter for Chart.js -->
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@2.0.0/dist/chartjs-adapter-date-fns.min.js"></script>

    <!-- Date picker -->
    <!-- Light Theme (default) -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <!-- Dark Theme -->
    <link id="flatpickrTheme" rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/themes/dark.css" disabled>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='main_stylesheet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='admin_stylesheet.css') }}">
    <title>{% block title %}Default Title{% endblock %}</title>
</head>

<body>
    <div class="container">
        
      <aside>
        <div class="top">
            <a href="{{ url_for('main.home') }}"><div class="logo"><h1>dataMULE</h1></div></a>

            <div class="close" id="close-btn" style="width: 2rem; height: 2rem;">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentcolor" class="bi bi-list" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                </svg>
            </div>
        </div>
        <div class="profile">
            <div class="info">
                <p>Hey, <b>{{user.first_name}}</b></p>
                <small class="text-muted">{{user.type}}</small>
            </div>
        </div>
        <div class="theme-selector-container">
            <div class="theme-selector">
                <span class="active">
                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-brightness-high-fill" viewBox="0 0 16 16">
                    <path d="M12 8a4 4 0 1 1-8 0 4 4 0 0 1 8 0zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
                    </svg>
                </span>
                <span>
                    <svg xmlns="http://www.w3.org/2000/svg"  fill="currentColor" class="bi bi-moon-fill" viewBox="0 0 16 16">
                        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
                    </svg>
                </span>
            </div>
        </div>
        
        {% if user.is_authenticated %}
            {% if user.type == 'admin' %}
                <div class="sidebar">
                    <!-- Display all teams for admin -->
                    {% if teams %}
                        {% for team in teams %}
                            <a href="/team/{{ team.id }}" class="{{ 'active' if request.path == url_for('main.team', id=team.id) else '' }}"><span>{{ team.name }}</span></a>
                        {% endfor %}
                    {% else %}
                        <p>No teams available.</p>
                    {% endif %}
                    </br>
                </div>
            {% elif user.type != 'athlete' %}
                <div class="sidebar">
                    <!-- Display associated teams for non-athlete users -->
                    {% if user.team_associations %}
                        {% for association in user.team_associations %}
                            <a href="/team/{{ association.team.id }}" class="{{ 'active' if request.path == url_for('main.team', id=association.team.id) else '' }}"><span>{{ association.team.name }}</span></a>
                        {% endfor %}
                    {% else %}
                        <p>No associated teams.</p>
                    {% endif %}
                    </br>
                </div>
            {% endif %}
        {% endif %}


        <a href="/logout"><span>Logout</span></a>
      </aside>
        <!-- ------------ End of Aside-------------- -->

        <main>
            {% block content %}
            <!-- Default content goes here -->
            {% endblock %}
        </main>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <script>
        const sideMenu = document.querySelector("aside");
        const closeBtn = document.querySelector("#close-btn");
        const menuBtn = document.querySelector("#menu-btn");
        const themeSelector = document.querySelector(".theme-selector");

        //show sidebar
        menuBtn.addEventListener('click', () =>{
            sideMenu.style.display = 'block'
        })
        //hide sidebar
        closeBtn.addEventListener('click', () =>{
            sideMenu.style.display = 'none'
        })
        // JavaScript for toggling themes and remembering the choice
        document.addEventListener("DOMContentLoaded", function() {
            const themeSelector = document.querySelector(".theme-selector");
            const currentTheme = localStorage.getItem('theme') || 'light'; // Default to light theme if not set

            // Apply the theme from local storage
            applyTheme(currentTheme);

            // Listen for theme change
            themeSelector.addEventListener('click', () => {
                const newTheme = document.body.classList.contains('dark-theme-variables') ? 'light' : 'dark';
                applyTheme(newTheme);
                localStorage.setItem('theme', newTheme); // Save theme preference in local storage
            });

            function applyTheme(theme) {
                const isDark = theme === 'dark';
                document.body.classList.toggle('dark-theme-variables', isDark);
                themeSelector.querySelector('span:nth-child(1)').classList.toggle('active', !isDark);
                themeSelector.querySelector('span:nth-child(2)').classList.toggle('active', isDark);
            }
        });
    </script>

    {% block extra_js %}
    <!-- Placeholder for page-specific JavaScript -->
    {% endblock %}
  
</body>
</html>

website/templates/create_notes_dashboard.html
{% extends 'base.html' %}

{% block title %}Create Note{% endblock %}

{% block content %}

<div class="top">
    <div class="menu" id="menu-btn" style="width: 2rem; height: 2rem;">
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentcolor" class="bi bi-list" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
        </svg>
    </div>
    <h1>New Note</h1>
</div>

<form class="two-col-dash" action="{{ url_for('main.new_note') }}" method="post">
    <div style="width: 100%;">
        <div class="input-box" style="width: 100%;">
            <input type="text" id="athleteSearch" onkeyup="filterList(this, document.getElementById('athleteList'))">
            <span>Lookup an Athlete</span>
        </div>
        <ul class="list-group" id="athleteList">
            {% for athlete in athletes %}
            <li class="list-group-item" onclick="checkRadio('athlete{{ athlete.id }}')">
                <input type="radio" id="athlete{{ athlete.id }}" name="athlete" value="{{ athlete.id }}">
                <label for="athlete{{ athlete.id }}">{{ athlete.first_name }} {{ athlete.last_name }}</label>
            </li>
            {% endfor %}
        </ul>
    </div>
    <!-- end of first column -->

    <div style="width: 100%;">
        <div class="input-box" style="width: 100%;">
            <input type="text" required="required" id="note" name="note">
            <span>Note</span>
        </div>

        <h2>Status Change</h2>
        <select class="form-control" id="status" name="status">
            <option value="0">Clear</option>
            <option value="1">Warning</option>
            <option value="2">Not Clear</option>
        </select>
        <div class="btn-cluster-ind" style="padding: 0;"><button value="Submit Note" type="submit" class="btn" id="submit-btn">Submit</button></div>
        <!-- end of second column -->
    </div>
</form>

{% endblock %}

{% block extra_js %}
<script>
    // Function to check a radio button when the li is clicked
    function checkRadio(radioId) {
            document.getElementById(radioId).checked = true;
        }

        $(document).ready(function() {
            // Code to add 'active' class to clicked li and remove from others
            $('#athleteList .list-group-item').on('click', function() {
                // Remove 'active' class from all items
                $('#athleteList .list-group-item').removeClass('active');
                
                // Add 'active' class to the clicked item
                $(this).addClass('active');
            });
        });

        // Code to prevent form submission if no athlete is selected
        document.querySelector('.two-col-dash').addEventListener('submit', function(event) {
            var radios = document.getElementsByName('athlete');
            var hasSelected = Array.from(radios).some(radio => radio.checked);

            if (!hasSelected) {
                alert('Please select an athlete.');
                event.preventDefault();  // Stop the form from submitting
            }
        });

        function filterList(inputElement, listElement) {
            let filter = inputElement.value.toUpperCase();
            let li = listElement.getElementsByTagName('li');

            for (let i = 0; i < li.length; i++) {
                let label = li[i].getElementsByTagName('label')[0];
                let txtValue = label.textContent || label.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    li[i].style.display = "";
                } else {
                    li[i].style.display = "none";
                }
            }
        }
</script>
{% endblock %}

website/templates/forgot_password.html
<!--
Jonathan Sosa
dataMULE
May - June 23
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>dataMULE - Forgot Password</title>
    <!-- CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='main_stylesheet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='sign_in_stylesheet.css') }}">
    <!-- fonts -->

</head>
<body>

    <!-- Main Body -->
    <main>
      <!-- Main container -->
      <div class="container-fluid">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
            <ul class=flashes>
            {% for message in messages %}
              <li>{{ message }}</li>
            {% endfor %}
            </ul>
          {% endif %}
        {% endwith %}
        <h1 class="text">dataMULE</h1>
        <h2 class="text">Forgot Password</h2>
        <form method='POST'>
          <div class="input-cluster">
            <div class="input-box">
              <input type="text" required="required" id="colby_id" name="colby_id">
              <span>Colby ID</span>
            </div>
          <button type="submit" class="btn" id="sign-in-btn">Recover</button>
        </form>
      </div>
  </main>
  
    
</body>
</html>